baseurl = "http://www.willfisher.xyz"
title = "willfisher"
theme = "minimal"
defaultcontentlanguage = "en"

[languages]
	[languages.en]
		languageName = "English"
		weight = 1
		[languages.en.params]
			country = "us"
		[languages.en.Taxonomies]
			tag = "tags"
			category = "categories"
		[[languages.en.menu.main]]
			name = "Home"
			url = "/"
			weight = 1

		[[languages.en.menu.main]]
			name = "About"
			url = "/about/"
			weight = 2

		[[languages.en.menu.main]]
			name = "Contact"
			url = "/contact/"
			weight = 3

		[[languages.en.menu.main]]
			name = "Math"
			url = "/categories/math"
			weight = 4

		[[languages.en.menu.main]]
			name = "Computer Science"
			url = "/categories/computer-science"
			weight = 5

		[[languages.en.menu.main]]
			name = "Languages"
			url = "/categories/languages"
			weight = 6
		[languages.en.Author]
			FullName = "Will Fisher"
			Email = "wfish454@gmail.com"
			Position = "Student"
	[languages.fr]
		languageName = "Français"
		weight = 2
		[languages.fr.params]
			country = "fr"
		[languages.fr.Taxonomies]
			plaque = "plaques"
			categorie = "catégories"
		[[languages.fr.menu.main]]
			name = "Accueil"
			url = "/"
			weight = 1

		[[languages.fr.menu.main]]
			name = "Me Connaître"
			url = "/me-connaitre/"
			weight = 2

		[[languages.fr.menu.main]]
			name = "Me Contacter"
			url = "/me-contacter/"
			weight = 3

		[[languages.fr.menu.main]]
			name = "Les Maths"
			url = "/catégories/maths"
			weight = 4

		[[languages.fr.menu.main]]
			name = "L'Informatique"
			url = "/catégories/informatique"
			weight = 5

		[[languages.fr.menu.main]]
			name = "Les Langues"
			url = "/catégories/langues"
			weight = 6
		[languages.fr.Author]
			FullName = "Will Fisher"
			Email = "wfish454@gmail.com"
			Position = "Élève"
		[languages.fr.blackfriday]
			angledQuotes = true
	[languages.es]
		languageName = "Español"
		weight = 3
		[languages.es.params]
			country = "es"
		[languages.es.Taxonomies]
			etiqueta = "etiquetas"
			categoria = "categorías"
		[[languages.es.menu.main]]
			name = "Inicio"
			url = "/"
			weight = 1

		[[languages.es.menu.main]]
			name = "Me Conocer"
			url = "/me-conocer/"
			weight = 2

		[[languages.es.menu.main]]
			name = "Me Contactar"
			url = "/me-contactar/"
			weight = 3

		[[languages.es.menu.main]]
			name = "Las Mates"
			url = "/categorías/mates"
			weight = 4

		[[languages.es.menu.main]]
			name = "La Informática"
			url = "/categorías/informática"
			weight = 5

		[[languages.es.menu.main]]
			name = "Los Idiomas"
			url = "/categorías/idiomas"
			weight = 6
		[languages.es.Author]
			FullName = "Will Fisher"
			Email = "wfish454@gmail.com"
			Position = "Estudiante"

[params]
	[[params.taglines]]
		tagline = "zeta2019.svg"
		type = "image"
		height = "50px"
	[[params.social]]
		name = "Github"
		icon = "fa fa-github fa-2x"
		weight = 1
		url = "https://github.com/willfisher/"
	[[params.social]]
		name = "LinkedIn"
		icon = "fa fa-linkedin fa-2x"
		weight = 2
		url = "https://www.linkedin.com/in/william-booth-fisher/"
